/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Root lib
    implementation(project(":kafka-streams-cassandra-state-store"))

    // This dependency is used by the application.
    implementation(libs.slf4j.simple)
    implementation(libs.kafka.streams)
    implementation(libs.scylladb.java.driver)
}

application {
    // Define the main class for the application.
    mainClass.set("dev.thriving.oss.kafka.streams.cassandra.state.store.example.wordcount.scylladb.WordCountDemo")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
